sudo: required
language: node_js
node_js:
- '8'
services: docker
before_install:
- docker image build -t gsd-frontend-backend .
- docker image save gsd-frontend-backend -o dockerimage.tar
- ls

script:
  - cd server && npm i
  - npm test
  - npm build
  - cd ../client && npm i && npm run build
  - cd ../server/public && mkdir appfiles && cp -r ../../client/build/* ./appfiles && ls

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: B3zQGenIxmia0+/IGTUdZLpy2yrbH/EV+gbHr9Y+cSg7XMJCUfFucvaPzlviznYB2uC6cXrZ4IHip9yC0z5GzYyWXcsYNrBzXG2cS8h7OrtG9H5mxvJXarozS2Lkb+k5XckDkfkE+HIKSrNMPJNkVWhDx1Eh3Ip7F9Hw6ZRsbksZwt7KtpD+prVXej/wsH2gyYoLn31uIhFKLtWA7AO6qlQ+4t+H5sQ6GHnJDslw6HUn4Hk9/RGOvKfJq+S5Fu+7ku+TQXOzxnmxdCmLMbgrlQZ+Q314WwOzN4l4r9V/cLzDn9a5fQil5afjscFO5ye/S/iIBOBiKEGbiezokKbd/ztXJiAxlFKTj8THXysxZTLSTaDu+ewYb1p0rI2IXkYYmjdTI5sMv42O1G7quz1ugCC6fgIGcv8WFx85bTVia0Y/SiJshuMb+zxVrU22TnZ7up6RG+rN+QF9eqKFxO14H7nSbcJLYj92jO1VumLbpdaM1OppGbojyo1xYnmmMyVRKUa+1mdf2ZdKD3nTBu1+GEYYoM5H9EqhIsjfFglRGhAgueBSkt2azlDmva/DH7akNlxIQoWyLAF2dJTnh+L/63LC+Nv71dxE5wGS/jUy0AE31j3LjXTmCZIVUWTZcDNAirU0rVYkrdz25KNzOX5jnAvZwdOfduz7zK7k9oePRlI=
  file: dockerimage.tar
  on:
    repo: Cojonas/gsd-frontend-backend
